// Wortliste – synchron mit src/data/words.ts
const wordList = [
  {id:'word-1',schriftdeutsch:'auch',mundart:'A',bedeutung:'ach, verstärkender Ausruf der die Verwunderung, Zweifel an einer Aussage und an Kritik betont: „(A), gää m(e) fo(a)tt!“ Lass mich in Ruh, mit deinem unglaublichen Gerede! „A, wou!“ wo, das stimmt so nicht.\nDer Gast will fortgehen. Der Hausherr will ihn zurückhalten und sagt: „A, gää fo(a)tt, bleib noch (e) bissi(e) doo!“',audioDatei:'Audio Beispiel 1',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-2',schriftdeutsch:'Auge',mundart:'Aach',bedeutung:'',audioDatei:'Audio Beispiel 2',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-3',schriftdeutsch:'Augen',mundart:'Aache',bedeutung:'',audioDatei:'',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-4',schriftdeutsch:'Augenblick',mundart:'Aachebligg',bedeutung:'',audioDatei:'',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-5',schriftdeutsch:'Augenlid',mundart:'am Aachebligg',bedeutung:'Das Augenlid',audioDatei:'',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-6',schriftdeutsch:'Augenlid',mundart:'Aachedeggel',bedeutung:'',audioDatei:'Audio Beispiel 6',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-7',schriftdeutsch:'Augenmaß',mundart:'Aachemoos',bedeutung:'',audioDatei:'Audio Beispiel 7',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-8',schriftdeutsch:'Eidotter, hartgekocht',mundart:'Aai, Aaiër',bedeutung:'Ei: „Ho(a)sch, dess Hinn-gel gääzt, dess hott (e) Aai ge(l)äischt.“\nEier, Gro. Pfl. Wen. Weib. Kraus. Aai(j)er, Raum AB. Neuh. Heig. Kgr. Ai(jr), Rob. Kromm. Part. Wies. Aar',audioDatei:'Audio Beispiel 8',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-9',schriftdeutsch:'Eidotter, hartgekocht',mundart:'Aaijerbiggel',bedeutung:'',audioDatei:'Audio Beispiel 9',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-10',schriftdeutsch:'Eiche, Eichen',mundart:'aaijern',bedeutung:'Eiche, Eichenholz',audioDatei:'Audio Beispiel 10',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-11',schriftdeutsch:'Eiche, Eichen',mundart:'Aasche',bedeutung:'',audioDatei:'Audio Beispiel 11',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-12',schriftdeutsch:'Eicheln',mundart:'Aaschel',bedeutung:'',audioDatei:'Audio Beispiel 12',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-13',schriftdeutsch:'Apotheke',mundart:'Aaschhörnsche',bedeutung:'Die Apotheke',audioDatei:'Audio Beispiel 13',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-14',schriftdeutsch:'Apfel',mundart:'Abdeegge',bedeutung:'Der Apfel',audioDatei:'Audio Beispiel 14',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-15',schriftdeutsch:'Apfel',mundart:'Abbel',bedeutung:'',audioDatei:'Audio Beispiel 15',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-16',schriftdeutsch:'Agathe',mundart:'Abgard',bedeutung:'Agathe (weiblicher Vorname)',audioDatei:'Audio Beispiel 16',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-17',schriftdeutsch:'Agathe',mundart:'Achedd',bedeutung:'',audioDatei:'Audio Beispiel 17',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-18',schriftdeutsch:'viel essen',mundart:'achelle',bedeutung:'',audioDatei:'Audio Beispiel 18',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-19',schriftdeutsch:'Elster, Eistem',mundart:'aachirren',bedeutung:'Die Elster (Vogel)',audioDatei:'Audio Beispiel 19',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-20',schriftdeutsch:'Elster, Elstern',mundart:'Addsel',bedeutung:'',audioDatei:'Audio Beispiel 20',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-21',schriftdeutsch:'Hühnerauge',mundart:'Addselaach',bedeutung:'',audioDatei:'Audio Beispiel 21',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-22',schriftdeutsch:'übel',mundart:'addselle',bedeutung:'Übel, schlecht',audioDatei:'Audio Beispiel 22',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-23',schriftdeutsch:'sagte man aus Schadenfreude',mundart:'aabschd',bedeutung:'Ausruf der Schadenfreude',audioDatei:'Audio Beispiel 23',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-24',schriftdeutsch:'Irden, aus Ton',mundart:'äarden',bedeutung:'Aus Ton, irden',audioDatei:'Audio Beispiel 24',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-25',schriftdeutsch:'Tontopf',mundart:'oan äardene Dibbe',bedeutung:'Ein Tontopf, -gefäß',audioDatei:'Audio Beispiel 25',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-26',schriftdeutsch:'Erde, Boden',mundart:'Ääre',bedeutung:'',audioDatei:'Audio Beispiel 26',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-27',schriftdeutsch:'Ernte',mundart:'Aärn',bedeutung:'Die Ernte',audioDatei:'Audio Beispiel 27',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-28',schriftdeutsch:'Wände mit Sprossen am Erntewagen',mundart:'Aärnlaadern',bedeutung:'',audioDatei:'Audio Beispiel 28',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-29',schriftdeutsch:'Erntewagen',mundart:'Aärnwoache',bedeutung:'Der Erntewagen',audioDatei:'Audio Beispiel 29',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-30',schriftdeutsch:'soeben, jetzt',mundart:'ääwe',bedeutung:'',audioDatei:'Audio Beispiel 30',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-31',schriftdeutsch:'jetzt reicht es mir',mundart:'ääwe loangd mersch',bedeutung:'',audioDatei:'Audio Beispiel 31',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-32',schriftdeutsch:'ob',mundart:'äbb',bedeutung:'',audioDatei:'Audio Beispiel 32',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-33',schriftdeutsch:'ehe',mundart:'äi',bedeutung:'',audioDatei:'Audio Beispiel 33',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-34',schriftdeutsch:'ehe',mundart:'Aibsche, Äibschen',bedeutung:'Ehe, bevor',audioDatei:'Audio Beispiel 34',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-35',schriftdeutsch:'Öl',mundart:'Äile',bedeutung:'',audioDatei:'Audio Beispiel 35',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-36',schriftdeutsch:'Öl',mundart:'Aile',bedeutung:'Das Öl',audioDatei:'Audio Beispiel 36',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-37',schriftdeutsch:'Rückstände aus der Ölmühle, Viehfutter',mundart:'Ailem',bedeutung:'',audioDatei:'Audio Beispiel 37',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-38',schriftdeutsch:'Elend, Not',mundart:'ailemisch',bedeutung:'Elend, Not, Mühsal',audioDatei:'Audio Beispiel 38',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-39',schriftdeutsch:'ehen',mundart:'äinder',bedeutung:'',audioDatei:'Audio Beispiel 39',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-40',schriftdeutsch:'Egge, eggen',mundart:'Äische, äische',bedeutung:'',audioDatei:'Audio Beispiel 40',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-41',schriftdeutsch:'Aas / übermütige, auch böse Person',mundart:'Oos (Plural Eeser)',bedeutung:'Aas; übermütige, auch böse Person',audioDatei:'Audio Beispiel 41',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-42',schriftdeutsch:'ab',mundart:'oab',bedeutung:'Ab, herunter',audioDatei:'Audio Beispiel 42',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-43',schriftdeutsch:'abgerissene Person',mundart:'oabgriesche',bedeutung:'Abgerissene, heruntergekommene Person',audioDatei:'Audio Beispiel 43',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-44',schriftdeutsch:'Schdeller',mundart:'Schdeller',bedeutung:'Schdeller (Begriff unklar)',audioDatei:'Audio Beispiel 44',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-45',schriftdeutsch:'abbekommen',mundart:'oabbkumme',bedeutung:'',audioDatei:'Audio Beispiel 45',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-46',schriftdeutsch:'abnehmbare Brettwand am Erntewagen',mundart:'oabnehmbare Brettwand',bedeutung:'Abnehmbare trapezförmige Brettwand vorn und hinten am Erntewagen',audioDatei:'Audio Beispiel 46',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-47',schriftdeutsch:'abdecken',mundart:'oabbreggele',bedeutung:'Abdecken, zudecken',audioDatei:'Audio Beispiel 47',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-48',schriftdeutsch:'abbröseln',mundart:'oabbreggele',bedeutung:'Abbröseln, zerbröckeln',audioDatei:'Audio Beispiel 48',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-49',schriftdeutsch:'abbrühen',mundart:'oabbrieje, beeje',bedeutung:'Abbrühen, mit heißem Wasser übergießen',audioDatei:'Audio Beispiel 49',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-50',schriftdeutsch:'Abend',mundart:'Oowend',bedeutung:'',audioDatei:'Audio Beispiel 50',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-51',schriftdeutsch:'abends',mundart:'oowens',bedeutung:'',audioDatei:'Audio Beispiel 51',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-52',schriftdeutsch:'Abendessen',mundart:'Noadässe',bedeutung:'Das Abendessen',audioDatei:'Audio Beispiel 52',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-53',schriftdeutsch:'aber',mundart:'äwwer',bedeutung:'Aber (Konjunktion)',audioDatei:'Audio Beispiel 53',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-54',schriftdeutsch:'Abfallstücke beim Sägen',mundart:'Schwoarde',bedeutung:'Abfallstücke beim Sägen von Balken und Brettern',audioDatei:'Audio Beispiel 54',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-55',schriftdeutsch:'Abfluss',mundart:'Oablaaf',bedeutung:'Der Abfluss',audioDatei:'Audio Beispiel 55',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-56',schriftdeutsch:'Abflussrinne, abgedeckt',mundart:'Doaul',bedeutung:'',audioDatei:'Audio Beispiel 56',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-57',schriftdeutsch:'abgeben',mundart:'oabgävwe',bedeutung:'',audioDatei:'Audio Beispiel 57',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-58',schriftdeutsch:'Getreide mit der Sichel aufraffen',mundart:'uffnemme',bedeutung:'Abgemähtes Getreide in Garbenstärke mit der Sichel aufraffen',audioDatei:'Audio Beispiel 58',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-59',schriftdeutsch:'Abweiser (Stein)',mundart:'Oabweiser',bedeutung:'Abgerundeter Stein zu beiden Seiten der Toreinfahrt',audioDatei:'Audio Beispiel 59',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-60',schriftdeutsch:'abgeschürft',mundart:'oabgeschunne',bedeutung:'Abgeschürft, aufgeschürft',audioDatei:'Audio Beispiel 60',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-61',schriftdeutsch:'abgestanden, schal',mundart:'oabgeschdoanne',bedeutung:'Abgestanden, schal (Getränk)',audioDatei:'Audio Beispiel 61',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-62',schriftdeutsch:'abgewetzt, glänzend',mundart:'schbäggisch',bedeutung:'Abgewetzt, glänzt vom Hautkontakt',audioDatei:'Audio Beispiel 62',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-63',schriftdeutsch:'abhängen',mundart:'oabhengge',bedeutung:'',audioDatei:'Audio Beispiel 63',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-64',schriftdeutsch:'abhanden kommen',mundart:'eubieße, eugbießd',bedeutung:'Abhanden kommen, verloren gehen',audioDatei:'Audio Beispiel 64',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-65',schriftdeutsch:'abhandeln',mundart:'oabluggse',bedeutung:'Abhandeln, feilschen',audioDatei:'Audio Beispiel 65',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-66',schriftdeutsch:'abhauen',mundart:'oabhaache',bedeutung:'Abhauen, weglaufen',audioDatei:'Audio Beispiel 66',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-67',schriftdeutsch:'abknöpfen',mundart:'oabgnebbe',bedeutung:'',audioDatei:'Audio Beispiel 67',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-68',schriftdeutsch:'abkratzen',mundart:'oabgraddsde',bedeutung:'',audioDatei:'Audio Beispiel 68',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-69',schriftdeutsch:'abkühlen',mundart:'oabkiele',bedeutung:'',audioDatei:'Audio Beispiel 69',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-70',schriftdeutsch:'abladen',mundart:'oabloare',bedeutung:'',audioDatei:'Audio Beispiel 70',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-71',schriftdeutsch:'Ablauf',mundart:'Oablaaf',bedeutung:'Der Ablauf',audioDatei:'Audio Beispiel 71',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-72',schriftdeutsch:'Ablegen von Garben',mundart:'Oabliäschder',bedeutung:'Ablegen von Garben mit der Mähmaschine',audioDatei:'Audio Beispiel 72',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-73',schriftdeutsch:'abmachen',mundart:'oabmache',bedeutung:'Abmachen, entfernen',audioDatei:'Audio Beispiel 73',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-74',schriftdeutsch:'Abmachung durch Handschlag',mundart:'oabmache',bedeutung:'Abmachung durch Handschlag bekräftigen',audioDatei:'Audio Beispiel 74',sprecher:'Luca Frei',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-75',schriftdeutsch:'bekräftigen',mundart:'euhaache',bedeutung:'Bekräftigen, versichern',audioDatei:'Audio Beispiel 75',sprecher:'Nina Schmid',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-76',schriftdeutsch:'abnehmen, wegnehmen',mundart:'oabnemme',bedeutung:'',audioDatei:'Audio Beispiel 76',sprecher:'Anna Meier',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-77',schriftdeutsch:'abnehmen, Gewicht verlieren',mundart:'oabnemme',bedeutung:'',audioDatei:'Audio Beispiel 77',sprecher:'Peter Keller',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-78',schriftdeutsch:'abpflücken',mundart:'oabblegge',bedeutung:'Abpflücken, Keime von Kartoffeln entfernen',audioDatei:'Audio Beispiel 78',sprecher:'Sara Huber',ort:'Wenigumstadt',datum:'21.05.2026'},
  {id:'word-79',schriftdeutsch:'Esel',mundart:'Äisel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-80',schriftdeutsch:'Alter',mundart:'Äll',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-81',schriftdeutsch:'der Älteste, die Älteste',mundart:'de Ällsd, di Ällsd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-82',schriftdeutsch:'Erdbeere, Erdbeeren',mundart:'Ärbel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-83',schriftdeutsch:'Getreideernte früher: Ablegen von Garben mit dem Ärfler der Mähmaschine',mundart:'ärfele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-84',schriftdeutsch:'maschinelle Ablegevorrichtung für Getreidegarben',mundart:'Ärfler',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-85',schriftdeutsch:'verwirrt',mundart:'ärr',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-86',schriftdeutsch:'Arme',mundart:'Ärm',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-87',schriftdeutsch:'zuerst, vorher',mundart:'ärschd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-88',schriftdeutsch:'irgendwo',mundart:'ärschendwoau',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-89',schriftdeutsch:'ärgern',mundart:'ärschern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-90',schriftdeutsch:'Arbeit',mundart:'Ärwedd',bedeutung:'Schaff deu Ärwedd!',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-91',schriftdeutsch:'seine Pflichten vernachlässigen',mundart:'Seu Ärwedd leische losse',bedeutung:'Der lessd seu Ärwedd leische unn gäid kassoade.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-92',schriftdeutsch:'Erbse, Erbsen',mundart:'Ärwes',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-93',schriftdeutsch:'Erbsen legen',mundart:'Ärwes läische',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-94',schriftdeutsch:'Buchenzweige zum Hochranken der Erbsen',mundart:'Ärwesreisisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-95',schriftdeutsch:'Hülsen der Erbsen',mundart:'Ärwesschludde',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-96',schriftdeutsch:'Asche',mundart:'Äsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-97',schriftdeutsch:'Esche, Eschen',mundart:'Äsche',bedeutung:'Esche, Eschen',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-98',schriftdeutsch:'Weg durch den Mosbacher Wald in Richtung Dorndiel',mundart:'Äschewääsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-99',schriftdeutsch:'Äste',mundart:'Ässd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-100',schriftdeutsch:'jemanden anerkennen, beachten',mundart:'ässdemiern',bedeutung:'Der wärrd iwwerhaubd nidd äsdemiird.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-101',schriftdeutsch:'Essen, essen',mundart:'Ässe, ässe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-102',schriftdeutsch:'einer, der aus der Reihe fällt, sich nicht normal benimmt',mundart:'Äwwerläddsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-103',schriftdeutsch:'alle, jeder',mundart:'all',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-104',schriftdeutsch:'los gehts, macht voran',mundart:'alla, allee',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-105',schriftdeutsch:'beide',mundart:'alle baad',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-106',schriftdeutsch:'dauernd',mundart:'alle Gebodd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-107',schriftdeutsch:'alle Augenblicke, ständig, wiederholt',mundart:'alle Ridd',bedeutung:'Der fengd alle Ridd woas oannerschd oau.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-108',schriftdeutsch:'Vorbehalte haben',mundart:'alles schäi unn guud, äwwer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-109',schriftdeutsch:'mitten in einer Tätigkeit aufhören',mundart:'alles schdäi unn leische losse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-110',schriftdeutsch:'genau das Gleiche',mundart:'s allersällwe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-111',schriftdeutsch:'jetzt, im Moment',mundart:'alleweil',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-112',schriftdeutsch:'andauernd',mundart:'alleweil',bedeutung:'andauernd',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-113',schriftdeutsch:'Egoist',mundart:'Allmeu',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-114',schriftdeutsch:'jeder',mundart:'allminoanner',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-115',schriftdeutsch:'allein',mundart:'alloa',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-116',schriftdeutsch:'ab und zu, manchmal',mundart:'allsemool',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-117',schriftdeutsch:'immerzu, als weiter',mundart:'allsfoard',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-118',schriftdeutsch:'Aschaffenburg',mundart:'Ascheboarsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-119',schriftdeutsch:'aus',mundart:'ass',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-120',schriftdeutsch:'aus dem, aus einem',mundart:'assemb',bedeutung:'aus dem/einem',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-121',schriftdeutsch:'Introvertiertheit überwinden',mundart:'ass sisch rausgäi',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-122',schriftdeutsch:'spontaner Ausruf, wenn man sich wegetan hat',mundart:'audsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-123',schriftdeutsch:'jammern über Schmerzen',mundart:'audsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-124',schriftdeutsch:'pellen, Samen aus ihren Schotten oder Hülsen herausholen',mundart:'ausbeenele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-125',schriftdeutsch:'ausbreiten',mundart:'ausbraare',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-126',schriftdeutsch:'gerissen, durchtrieben',mundart:'ausgeeqqd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-127',schriftdeutsch:'ausgesaugt',mundart:'ausgesubbd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-128',schriftdeutsch:'außerhalb der Gepflogenheit, der Normen',mundart:'ausscheern, ausschierisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-129',schriftdeutsch:'soeben, im Augenblick',mundart:'awel, aweil',bedeutung:'soeben, im Augenblick',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-130',schriftdeutsch:'Kategorie-Marker',mundart:'B',bedeutung:'Kategorie-Marker',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-131',schriftdeutsch:'altes Gebäude',mundart:'Baajes',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-132',schriftdeutsch:'in Lake eingelegte Knochen mit Fleischresten',mundart:'Baasflasch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-133',schriftdeutsch:'Kleber, Kleister',mundart:'Babb',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-134',schriftdeutsch:'kleben',mundart:'babbe, s babbd',bedeutung:'es klebt',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-135',schriftdeutsch:'ein Stück Pappe',mundart:'Babbedeggel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-136',schriftdeutsch:'Klettenlabkraut',mundart:'Babbgraud',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-137',schriftdeutsch:'klebrig, verdreckt',mundart:'babbisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-138',schriftdeutsch:'Mensch, der oft anderen schadet',mundart:'Babbsagg',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-139',schriftdeutsch:'Papa',mundart:'Babba',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-140',schriftdeutsch:'reden, Schwätzchen halten',mundart:'babbele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-141',schriftdeutsch:'was du nicht sagst, unglaubliche Neuigkeit',mundart:'babbel nidd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-142',schriftdeutsch:'Es hilft nichts',mundart:'s badd niggs, s hodd gebadd',bedeutung:'es hat geholfen',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-143',schriftdeutsch:'Alles Bitten ist umsonst',mundart:'S helfd unn badd alles niggs',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-144',schriftdeutsch:'Das Flehen war umsonst',mundart:'S hodd alles niggs gebadd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-145',schriftdeutsch:'Partei, Parteien',mundart:'Baddei, Baddeie',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-146',schriftdeutsch:'patent, angenehme Person',mundart:'baddend',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-147',schriftdeutsch:'einige',mundart:'Baddie (oa Badie)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-148',schriftdeutsch:'Münzen in der Kindersprache',mundart:'Badds',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-149',schriftdeutsch:'Klaps',mundart:'Baddsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-150',schriftdeutsch:'rechte Hand (Kind gibt Erwachsenem die Hand)',mundart:'Baddschhenn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-151',schriftdeutsch:'einer der dumm daher redet',mundart:'Bäbbeler, Dummbäbbeler',bedeutung:'Einer der dumm daher redet, faselt. „Oann Bäbbeler woorer schonn immer.“',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-152',schriftdeutsch:'beten',mundart:'bääre',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-153',schriftdeutsch:'Tragbahre für Brot zum Backen',mundart:'Bäärn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-154',schriftdeutsch:'Besen',mundart:'Bääsem',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-155',schriftdeutsch:'Besenstiel',mundart:'Bääsemschdiel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-156',schriftdeutsch:'Besenreisig',mundart:'Bääsemreisisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-157',schriftdeutsch:'im Moment',mundart:'emm Aachebligg',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-158',schriftdeutsch:'Ei, Eier',mundart:'Aai, Aaijer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-159',schriftdeutsch:'Eichhörnchen',mundart:'Aaschhärrnsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-160',schriftdeutsch:'Apotheke',mundart:'Abedeege',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-161',schriftdeutsch:'Klo, Toilette',mundart:'Aboard',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-162',schriftdeutsch:'jemanden aufziehen, ärgern',mundart:'achiern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-163',schriftdeutsch:'stehlen',mundart:'addsele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-164',schriftdeutsch:'übel',mundart:'ääbschd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-165',schriftdeutsch:'sagte man aus Schadenfreude',mundart:'äädsch',bedeutung:'Ausruf der Schadenfreude',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-166',schriftdeutsch:'irden, aus Ton',mundart:'äärden',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-167',schriftdeutsch:'Tontopf',mundart:'oan äärdene Dibbe, - Hoawe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-168',schriftdeutsch:'Ernte',mundart:'Äärn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-169',schriftdeutsch:'Wände mit Sprossen am Erntewagen',mundart:'Äärnlaadern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-170',schriftdeutsch:'Erntewagen',mundart:'Äärnwoache',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-171',schriftdeutsch:'etwas',mundart:'äbbes',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-172',schriftdeutsch:'Öfchen',mundart:'Äibsche, Äibschen',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-173',schriftdeutsch:'Rückstände aus der Ölmühle, Viehfutter',mundart:'Äilekuche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-174',schriftdeutsch:'Elend, Not',mundart:'Äilend',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-175',schriftdeutsch:'schwach, zurückgeblieben',mundart:'äilennisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-176',schriftdeutsch:'kastriertes männliches Mastschwein',mundart:'Boarsch (lang)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-177',schriftdeutsch:'junger Mann',mundart:'Boarschd (kurz)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-178',schriftdeutsch:'Bürgermeister',mundart:'Boarschemoasder',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-179',schriftdeutsch:'naiver, etwas einfältiger Mensch',mundart:'Boaudel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-180',schriftdeutsch:'beizeiten',mundart:'boazeire',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-181',schriftdeutsch:'Puppe',mundart:'Bobbe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-182',schriftdeutsch:'Maiskolben',mundart:'Maisbobbe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-183',schriftdeutsch:'neugeborenes Kind',mundart:'Bobbelsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-184',schriftdeutsch:'Hintern eines Kindes',mundart:'Bobbes',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-185',schriftdeutsch:'Hut in einer bestimmten runden Form',mundart:'Boggelhardsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-186',schriftdeutsch:'rütteln und rumpeln an der Türe oder dem Fensterladen',mundart:'bollern, gebollerd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-187',schriftdeutsch:'Bommel, Quaste',mundart:'Bommbel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-188',schriftdeutsch:'Bahn, Schlittenbahn',mundart:'Boo, Schliereboo',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-189',schriftdeutsch:'einen Pfad zum sicheren Gehen in den Schnee fegen',mundart:'Boo keern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-190',schriftdeutsch:'Bogen',mundart:'Booche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-191',schriftdeutsch:'Vogelscheuche auf Äckern und Bäumen',mundart:'Boods, Kärscheboods',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-192',schriftdeutsch:'Loch (Zielpunkt) beim Räuber- und Gendarmenspiel',mundart:'Boods',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-193',schriftdeutsch:'Bohnen',mundart:'Boone',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-194',schriftdeutsch:'Bohnenstange, Bohnenstangen',mundart:'Booneschdoange',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-195',schriftdeutsch:'Bohnenhülsen',mundart:'Booneschludde',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-196',schriftdeutsch:'Bohnensuppe',mundart:'Boonesubbe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-197',schriftdeutsch:'dickes Brett, Bohle',mundart:'Boord',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-198',schriftdeutsch:'Wand, mit der ein Raum unterteilt wurde',mundart:'Boordwenn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-199',schriftdeutsch:'bohren',mundart:'boorn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-200',schriftdeutsch:'Speicher',mundart:'Borrm',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-201',schriftdeutsch:'Erdboden',mundart:'Borrm',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-202',schriftdeutsch:'Boden eines Gefäßes',mundart:'Borrm',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-203',schriftdeutsch:'Boden eines Gefäßes gerade bedeckt',mundart:'Borrm bedeggd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-204',schriftdeutsch:'Possen, Unsinn',mundart:'Bosse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-205',schriftdeutsch:'heimwerken, basteln, ausprobieren',mundart:'bossele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-206',schriftdeutsch:'breit',mundart:'braad',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-207',schriftdeutsch:'breittreten, Neuigkeiten weitererzählen',mundart:'braaddrääre',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-208',schriftdeutsch:'breiten, Mist mit der Gabel auf dem Acker gleichmäßig verstreuen',mundart:'braare',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-209',schriftdeutsch:'Schlamm, Matsch, matschig',mundart:'Brabbs, brabbsisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-210',schriftdeutsch:'Brett',mundart:'Brääd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-211',schriftdeutsch:'breiter',mundart:'bräärer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-212',schriftdeutsch:'Brezel',mundart:'Bräddsel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-213',schriftdeutsch:'brechen, sich übergeben, gebrochen',mundart:'bräsche, gebroche (sich übergeben)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-214',schriftdeutsch:'Äpfel und Birnen abmachen',mundart:'bräsche, gebroche (Äpfel abmachen)',bedeutung:'Die schennsde Ebbel bräsche merr raus, die oannern schille merr runner. / Die Äpfel „gebrochen“ werden',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-215',schriftdeutsch:'umgehängter Sack in den Äpfel „gebrochen“ werden',mundart:'Bräschsagg',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-216',schriftdeutsch:'Klicker',mundart:'Biggel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-217',schriftdeutsch:'mit Klickern spielen',mundart:'Biggelsches schbiele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-218',schriftdeutsch:'Büchse, Dose',mundart:'Biggse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-219',schriftdeutsch:'Dosenöffner',mundart:'Biggseeffner',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-220',schriftdeutsch:'ich bin',mundart:'isch binn',bedeutung:'isch binn, isch benn (Mosbach, Dorndiel), isch seu (Pflaumheim)',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-221',schriftdeutsch:'Binde',mundart:'Binne',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-222',schriftdeutsch:'binden, gebunden',mundart:'binne, gebunne',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-223',schriftdeutsch:'Erntemaschine für Getreide',mundart:'Binner',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-224',schriftdeutsch:'Krawatte',mundart:'Binner',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-225',schriftdeutsch:'Bütte',mundart:'Birre',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-226',schriftdeutsch:'Büsche',mundart:'Bisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-227',schriftdeutsch:'bügeln',mundart:'bischele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-228',schriftdeutsch:'Bügeleisen',mundart:'Bischeleise',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-229',schriftdeutsch:'kleines Buch',mundart:'Bischelsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-230',schriftdeutsch:'Bücher',mundart:'Bischer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-231',schriftdeutsch:'plättschern',mundart:'bläddschern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-232',schriftdeutsch:'Teppichklopfer',mundart:'Debbischbläddscher',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-233',schriftdeutsch:'schweres spezielles Holzwerkzeug zum Festklopfen des Mistes auf dem Wagen',mundart:'Missdbläddscher',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-234',schriftdeutsch:'blöde',mundart:'bläid',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-235',schriftdeutsch:'bezahlen müssen',mundart:'bläsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-236',schriftdeutsch:'weißer Stirnfleck bei Haustieren',mundart:'Bläss',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-237',schriftdeutsch:'abwertend für Gesicht',mundart:'Bläss',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-238',schriftdeutsch:'Kopfverletzung',mundart:'Bläss',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-239',schriftdeutsch:'pflücken',mundart:'blegge',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-240',schriftdeutsch:'Pflänzchen',mundart:'Blensje, Blennsjen',bedeutung:'Die Blensjen kumme dessjoor nidd vonn de Ääre weg.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-241',schriftdeutsch:'Blätter',mundart:'Blerrer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-242',schriftdeutsch:'von Futterrüben einen Teil der Blätter als Futter für die Rinder entfernen',mundart:'Blerrer mache',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-243',schriftdeutsch:'umblättern',mundart:'blerrern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-244',schriftdeutsch:'Blitz',mundart:'Blidds',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-245',schriftdeutsch:'blitzblau',mundart:'bliddsbloo',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-246',schriftdeutsch:'blühen',mundart:'blimme',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-247',schriftdeutsch:'Blümchen',mundart:'Blimmschen',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-248',schriftdeutsch:'blind',mundart:'blinn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-249',schriftdeutsch:'Blatt',mundart:'Bload',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-250',schriftdeutsch:'blamieren',mundart:'bloamiern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-251',schriftdeutsch:'Pflanze, anpflanzen',mundart:'Bloanse, bloanse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-252',schriftdeutsch:'Pflaumheim',mundart:'Bloaume',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-253',schriftdeutsch:'bloß, unbekleidet, nackt',mundart:'bloauß',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-254',schriftdeutsch:'ohne Kopfbedeckung',mundart:'bloaußkebbisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-255',schriftdeutsch:'nur',mundart:'bloauß',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-256',schriftdeutsch:'blau',mundart:'bloo',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-257',schriftdeutsch:'Plage, plagen, anstrengen',mundart:'Blooch, blooche',bedeutung:'Der hodd sisch gebloochd wie oann Hund.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-258',schriftdeutsch:'beben, wackeln',mundart:'bääwe',bedeutung:'Di Ääre hodd soau gebääbd, dass s Bild von de Wenn gefalle iss.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-259',schriftdeutsch:'unfreundlich widersprechen, freche Antwort geben',mundart:'bäddse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-260',schriftdeutsch:'jemand, der ständig zedert',mundart:'Bäddsniggel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-261',schriftdeutsch:'Bäcker',mundart:'Bägger',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-262',schriftdeutsch:'böse',mundart:'bäis',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-263',schriftdeutsch:'jemandem Schaden zufügen',mundart:'bäisdoau',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-264',schriftdeutsch:'gesundheitlich sehr schlecht gehen',mundart:'bäismache',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-265',schriftdeutsch:'Zeug, das nichts taugt, Bettel',mundart:'Bäll',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-266',schriftdeutsch:'Pappel',mundart:'Bälle',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-267',schriftdeutsch:'betteln, gebettelt',mundart:'bälle, gebälld',bedeutung:'isch häbb gebidd unn gebälld',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-268',schriftdeutsch:'Schnorrer, hartnäckiger Bittender',mundart:'Bällsagg',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-269',schriftdeutsch:'Bürzel',mundart:'Bärdsel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-270',schriftdeutsch:'Birke',mundart:'Bärge',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-271',schriftdeutsch:'Garbe, Garben, Getreidebündel',mundart:'Bärre',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-272',schriftdeutsch:'Berg, Anhöhe, Berge',mundart:'Bärsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-273',schriftdeutsch:'bergab',mundart:'bärschoab',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-274',schriftdeutsch:'bergauf',mundart:'bärschnuff',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-275',schriftdeutsch:'bergab',mundart:'bärschnunner',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-276',schriftdeutsch:'bergauf',mundart:'bärschuff',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-277',schriftdeutsch:'Bürste, Bürsten',mundart:'Bärschde',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-278',schriftdeutsch:'bürsten',mundart:'bärschde',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-279',schriftdeutsch:'kleine Bürste',mundart:'Bärschdsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-280',schriftdeutsch:'abwertend: schmächtiger Jugendlicher',mundart:'Bärschdsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-281',schriftdeutsch:'Pech',mundart:'Bäsch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-282',schriftdeutsch:'überrascht sein, erstaunt sein',mundart:'baff',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-283',schriftdeutsch:'asoziale Menschengruppe',mundart:'Bagasch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-284',schriftdeutsch:'Backe (Wange)',mundart:'Bagge',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-285',schriftdeutsch:'backen',mundart:'bagge',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-286',schriftdeutsch:'Holztrog zum Teigansetzen',mundart:'Baggdrooch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-287',schriftdeutsch:'gemeinschaftlich genutzter Backofen',mundart:'Bagges',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-288',schriftdeutsch:'Backstein, Ziegelstein',mundart:'Baggschdoa',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-289',schriftdeutsch:'Backschüssel',mundart:'Baggschissel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-290',schriftdeutsch:'einer, der das Leben nicht ernst nimmt',mundart:'Baijass',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-291',schriftdeutsch:'Bäuche',mundart:'Baisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-292',schriftdeutsch:'Ball, Bälle',mundart:'Balle',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-293',schriftdeutsch:'Ballen',mundart:'Balle',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-294',schriftdeutsch:'folgen, gehorchen',mundart:'barriern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-295',schriftdeutsch:'strapazierfähiges Gewebe',mundart:'Barschend',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-296',schriftdeutsch:'Nebengebäude',mundart:'Bau',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-297',schriftdeutsch:'Barbara, Babette',mundart:'Bawwedd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-298',schriftdeutsch:'Rückstände in der Nase',mundart:'Beebel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-299',schriftdeutsch:'in der Nase bohren',mundart:'beebele',bedeutung:'Der hodd dauernd gebeebeled unn doann de Beebel enns Maul geschdeggd.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-300',schriftdeutsch:'abbrühen',mundart:'beeje',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-301',schriftdeutsch:'Bäume',mundart:'Beem',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-302',schriftdeutsch:'jemanden zu überreden versuchen, ihn quälen',mundart:'blooche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-303',schriftdeutsch:'jemand, der einen anderen andauernd mit allen Mitteln überreden will',mundart:'Bloochgeisd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-304',schriftdeutsch:'nackt und bloß',mundart:'blodd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-305',schriftdeutsch:'ohne Geld sein',mundart:'blodd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-306',schriftdeutsch:'rauchen',mundart:'bloddsche',bedeutung:'Der hodd gebloddschd wi oann Schlood.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-307',schriftdeutsch:'so stark regnen, dass die Pflanzen ganz am Boden liegen',mundart:'bloddsche',bedeutung:'S hood sou gebloddschd, dass de koa Blennsjen mäi gesäie hosdd.',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-308',schriftdeutsch:'Dünnschiss bei Kühen (im Herbst, wenn viele Rübenblätter verfüttert wurden)',mundart:'blorrern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-309',schriftdeutsch:'Blase, blasen',mundart:'Bloose, bloose',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-310',schriftdeutsch:'Pflug',mundart:'Blugg',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-311',schriftdeutsch:'Zwei mit einer Schraube verbundene Rundhölzer, auf der ein Pflug von daheim bis auf den Acker geschleift wurde',mundart:'Bluggschlaafe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-312',schriftdeutsch:'Pflugschar',mundart:'Bluggschoar',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-313',schriftdeutsch:'Blume',mundart:'Blumme',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-314',schriftdeutsch:'Blumentopf',mundart:'Blummedibbe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-315',schriftdeutsch:'Blumenkohl',mundart:'Blummekoaul',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-316',schriftdeutsch:'Blutwurst',mundart:'Blunse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-317',schriftdeutsch:'Blut',mundart:'Bluud',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-318',schriftdeutsch:'bluten, blutig',mundart:'bluure, bluurisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-319',schriftdeutsch:'großer Wiesenknopf (Heilkraut)',mundart:'Bluudsdrebbschen',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-320',schriftdeutsch:'bei, beim',mundart:'boa (kurz), boamm',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-321',schriftdeutsch:'Bein, Beine',mundart:'Boa (lang)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-322',schriftdeutsch:'Bad',mundart:'Boad',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-323',schriftdeutsch:'bald',mundart:'boal',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-324',schriftdeutsch:'Baum',mundart:'Boam',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-325',schriftdeutsch:'Baumacker',mundart:'Boamagger',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-326',schriftdeutsch:'baumeln',mundart:'boammbele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-327',schriftdeutsch:'Eisenbahn',mundart:'Boan (lang)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-328',schriftdeutsch:'Bahnhof',mundart:'Boanhoauf',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-329',schriftdeutsch:'Bankert, ungezogener Junge',mundart:'Boanggerd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-330',schriftdeutsch:'beieinander',mundart:'boanoanner',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-331',schriftdeutsch:'rüstig, gesund im Alter',mundart:'noch guud boanoanner seu',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-332',schriftdeutsch:'bar',mundart:'boar',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-333',schriftdeutsch:'Bart',mundart:'Board',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-334',schriftdeutsch:'niedliches Kleinkind',mundart:'Boardsel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-335',schriftdeutsch:'purzeln',mundart:'boardsele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-336',schriftdeutsch:'Purzelbaum',mundart:'Boardselboam',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-337',schriftdeutsch:'baden',mundart:'boare',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-338',schriftdeutsch:'barfuß',mundart:'boarfissisch',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-339',schriftdeutsch:'Abteilung in der Scheune, tiefer liegend, manchmal vorne bis zu einer Höhe von 2 m abgemauert, um Laub (Schraasel) zum Einstreuen zu lagern',mundart:'Boarn',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-340',schriftdeutsch:'Birnen',mundart:'Beern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-341',schriftdeutsch:'Beeren',mundart:'Beern',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-342',schriftdeutsch:'jemanden erschrecken, Angst machen',mundart:'beeze',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-343',schriftdeutsch:'es riecht nach Ziegenbock',mundart:'s beggseld',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-344',schriftdeutsch:'behalten',mundart:'behoale',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-345',schriftdeutsch:'Beutel',mundart:'Beidel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-346',schriftdeutsch:'dumme Person',mundart:'Dummbeidel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-347',schriftdeutsch:'Geldbörse',mundart:'Geldbeidel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-348',schriftdeutsch:'Peitsche, Peitschen',mundart:'Beidsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-349',schriftdeutsch:'bei ihm',mundart:'beiemm',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-350',schriftdeutsch:'sich verspäten, nicht rechtzeitig dasein',mundart:'beikumme, der kimmd nidd bei',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-351',schriftdeutsch:'dem ist keiner gewachsen',mundart:'demm kimmd koan bei',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-352',schriftdeutsch:'Fensterflügel oder Tür anlehnen, zumachen',mundart:'beimache',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-353',schriftdeutsch:'Einladung: Komm! Komm her zu uns!',mundart:'mach dich bei',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-354',schriftdeutsch:'schwer zu bearbeitender (toniger) Ackerboden',mundart:'bellsische Ägger',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-355',schriftdeutsch:'läuten durch das Schlagen des Klöppels an die ruhende Glocke',mundart:'bemmbele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-356',schriftdeutsch:'Ausscheller, Glöckner',mundart:'Bembler',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-357',schriftdeutsch:'Holzprügel',mundart:'Bengel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-358',schriftdeutsch:'Sitzbank, Sitzbänke',mundart:'Bengg',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-359',schriftdeutsch:'Bindfaden',mundart:'Bennel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-360',schriftdeutsch:'Schnürsenkel',mundart:'Schuhbennel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-361',schriftdeutsch:'Kordel zum Abbinden der Würste',mundart:'Worschdbennel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-362',schriftdeutsch:'Pinsel',mundart:'Bennsel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-363',schriftdeutsch:'Nikolaus',mundart:'Bennsniggel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-364',schriftdeutsch:'Obstboden, flacher runder Kuchen',mundart:'Berrmsche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-365',schriftdeutsch:'Bach, Bäche',mundart:'Besch (die Besch!)',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-366',schriftdeutsch:'betrügen, betrogen',mundart:'bescheiße, beschisse',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-367',schriftdeutsch:'Betrug',mundart:'Beschiss',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-368',schriftdeutsch:'Ungeziefer an Nutzpflanzen',mundart:'Beschiss',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-369',schriftdeutsch:'betrunken',mundart:'besuffe',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-370',schriftdeutsch:'bewandert, mit großem Wissen',mundart:'bewoannerd',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-371',schriftdeutsch:'rechtzeitig, früh',mundart:'bezeid',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-372',schriftdeutsch:'bezahlen',mundart:'bezoale',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-373',schriftdeutsch:'Hühnerkrankheit',mundart:'Bibbs',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-374',schriftdeutsch:'erkranktes Huhn',mundart:'Bibbshinggel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-375',schriftdeutsch:'Jemand, der völlig passiv ist',mundart:'Bibbshinggel',bedeutung:'Des iss doch oa Bibbshinggel!',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-376',schriftdeutsch:'bizzeln',mundart:'biddsele',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-377',schriftdeutsch:'Biene, Bienen',mundart:'Bie',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-378',schriftdeutsch:'Ruf, um die Hühner anzulocken',mundart:'bie bie bie',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-379',schriftdeutsch:'kleiner Bub, kleine Buben',mundart:'Biebsche, Biebschen',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-380',schriftdeutsch:'bieten, geboten',mundart:'biere, gebodde',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-381',schriftdeutsch:'biegen',mundart:'biesche',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-382',schriftdeutsch:'Bügel',mundart:'Bieschel',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-383',schriftdeutsch:'büßen',mundart:'bieße',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-384',schriftdeutsch:'Flanellbettwäsche',mundart:'Biewer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-385',schriftdeutsch:'Biber',mundart:'Biewer',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''},
  {id:'word-386',schriftdeutsch:'bücken',mundart:'bigge',bedeutung:'',audioDatei:'',sprecher:'',ort:'Wenigumstadt',datum:''}
];

export { wordList, wordList as fullWordList };
export default wordList;
